# LangGraph Agent Workflow
# This file will contain the LangGraph state definition and agent nodes

from typing import TypedDict

class State(TypedDict):
    """
    State object passed through the LangGraph workflow.
    
    Attributes:
        user_msg: The message received from the user
        agent_response: The response generated by the agent
    """
    user_msg: str
    agent_response: str
